### PR TITLE
added handwritten notes for linux all linux lectures

### PR DESCRIPTION
**Pull request by Ankur1493**

### CODE REVIEW

**Comment by Ankur1493** [comment]
have added handwritten notes for all linux lectures and thanks apoorv for making those lectures 
I am learning devops but stil want to learn about web dev little bit eagerly waiting for your course

**Review by apoorv-on-git — CHANGES_REQUESTED** [review]
Hi Ankur, thanks for the handwritten notes. Can you please change the names of all the PDF files to "notes.pdf" and update the PR? Thanks!

**Comment by Ankur1493** [comment]
Done captain

**Review by apoorv-on-git — CHANGES_REQUESTED** [review]
Hi Ankur, thanks again for the changes, however in your commit - it says that a ".README.md.swp" file is added, probably since you exited some file with unsaved changes. Can you remove that file from the commit? Thanks again!

**Comment by Ankur1493** [comment]
I will totally do it today, I was busy completing file for college practicals

**Pull request closed without merging**
