### PR TITLE
added content to 04-users-and-permissions

### PR DESCRIPTION
**Pull request by Deepjyoti-Sarmah**
Added topics like: 

- [x] Users-and-permissions
- [x] What are users and groups?
- [x] Managing users
- [x] Manage groups
- [x] Superuser access
- [x] File permissions & ownership
- [x]  How to manage permissions
- [x]  Sticky bit

### CODE REVIEW

**Review by danishhansari — APPROVED** [review]
Awesome contribution Thank you

Don't make giant PR at once

**Comment by Deepjyoti-Sarmah** [comment]
@danishhansari  Thank you for the review 
And I shall consider your suggestion

**Review by apoorv-on-git — APPROVED** [review]
Good work!

**Comment by danishhansari** [comment]
> Good work!

bro upload a video waiting so eagerly

**Pull request merged**
